
services:

  # --- IDENTITY SERVICE, DATABASE & MIGRATIONS ---
  identity-cache:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  identity-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_password
      POSTGRES_DB: identity_db
    ports:
      - "5051:5432"
    volumes:
      - identity_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identity_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  identity-migrate:
    image: migrate/migrate
    volumes:
      # Relative path goes into the identity-service directory
      - ./identity-service/migrations:/migrations
    command:
      -path=/migrations
      -database="postgres://identity_user:identity_password@identity-db:5432/identity_db?sslmode=disable"
      up
    depends_on:
      identity-db:
        condition: service_healthy

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      identity-cache:
        condition: service_healthy
      identity-db:
        condition: service_healthy
      identity-migrate:
        condition: service_completed_successfully
    environment:
      - POSTGRES_URL=postgres://identity_user:identity_password@identity-db:5432/identity_db?sslmode=disable
      - REDIS_URL=redis://identity_cache:6379
      - JWT_SECRET=68a5f0e0-6bf0-4b25-8c38-5b9c706bf21d
    networks:
      - app_network


  # --- COMMUNICATION SERVICE, DATABASE & MIGRATIONS ---
  communication-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: comms_user
      POSTGRES_PASSWORD: comms_password
      POSTGRES_DB: communication_db
    ports:
      - "5052:5432"
    volumes:
      - comms_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comms_user -d communication_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  communication-migrate:
    image: migrate/migrate
    volumes:
      # Relative path goes into the communication-service directory
      - ./communication-service/migrations:/migrations
    command:
      -path=/migrations
      -database="postgres://comms_user:comms_password@communication-db:5432/communication_db?sslmode=disable"
      up
    depends_on:
      communication-db:
        condition: service_healthy

  # communication-service:

  
volumes:
  redis_data:
  identity_pg_data:
  comms_pg_data:

networks:
  app_network:
    driver: bridge