services:
  # --- COMMON: NATS JETSTREAM ---
  nats-jetstream:
    image: nats:2.10-alpine
    command: "-js -sd /data --http_port 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/nats-data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- IDENTITY: SERVICE, CACHE, DATABASE & MIGRATIONS ---
  identity-cache:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - identity_redis_data:/identity_redis_data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  identity-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_password
      POSTGRES_DB: identity_db
    ports:
      - "5051:5432"
    volumes:
      - identity_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "identity_user", "-d", "identity_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  identity-migrate:
    image: migrate/migrate
    volumes:
      # Relative path goes into the identity-service directory
      - ./cmd/identity-api-service/migrations:/migrations
    command: -path=/migrations
      -database="postgres://identity_user:identity_password@identity-db:5432/identity_db?sslmode=disable"
      up
    depends_on:
      identity-db:
        condition: service_healthy

  identity-service:
    build:
      context: ./
      dockerfile: cmd/identity-api-service/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://identity-cache:6379
      - JWT_SECRET=68a5f0e0-6bf0-4b25-8c38-5b9c706bf21d
      - POSTGRES_URL=postgres://identity_user:identity_password@identity-db:5432/identity_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      nats-jetstream:
        condition: service_healthy
      identity-cache:
        condition: service_healthy
      identity-db:
        condition: service_healthy
      identity-migrate:
        condition: service_completed_successfully

  # --- COMMUNICATION: SERVICE, DATABASE & MIGRATIONS ---
  communication-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: comms_user
      POSTGRES_PASSWORD: comms_password
      POSTGRES_DB: communication_db
    ports:
      - "5052:5432"
    volumes:
      - comms_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "comms_user", "-d", "communication_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  communication-migrate:
    image: migrate/migrate
    volumes:
      # Relative path goes into the communication-service directory
      - ./cmd/communication-api-service/migrations:/migrations
    command: -path=/migrations
      -database="postgres://comms_user:comms_password@communication-db:5432/communication_db?sslmode=disable"
      up
    depends_on:
      communication-db:
        condition: service_healthy

  # communication-service:

volumes:
  nats-data:
  identity_redis_data:
  identity_pg_data:
  comms_pg_data:
