-- 1. crete user table
create table users 
(
    -- main
    id uuid primary key,
    username varchar(20) unique not null,
    phone varchar(20) not null,

    -- common information
    first_name varchar(20) null,
    last_name varchar(20) null,
    birth_date date null,
    bio_description varchar(255) null,
    profile_photo_url varchar(255) null,

    -- timestamps
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null
);

create index idx_user_username on users(username);
create index idx_user_phone on users(phone);

comment on table users is 'communicate "users" table stores common user information for other users';
comment on column users.id is 'unique user id that matches with users(id) of identity db, (NOTICE that we do not generate id by default, it takes after identity user creation)';



-- 2. create types of chat enum
create type chat_type as enum ('direct', 'group');



-- 3. create chat table that stores common info
create table chats
(
    -- main information
    id uuid generated by default as identity primary key,
    type chat_type not null,
    created_at timestamp with time zone default current_timestamp not null,

    -- title of the chat is nullable for direct chats (computed from the other user's name), but mandatory for group chats
    title varchar(100)
);



-- 4. create junction chat table
create table participants
(
    chat_id uuid not null references chats(id) on update cascade on delete cascade,
    user_id uuid not null references users(id) on update cascade on delete cascade,
    joined_at timestamp with time zone default current_timestamp not null,

    primary key (chat_id, user_id)
);

create index idx_participant_lookup on participants(user_id);

comment on table participants is '"participans" is junction table between chats (direct or group) and users';



-- 5. create types of message enum
create type message_type as enum ('plain text', 'photo', 'video', 'album');



-- 6. create message table
create table messages
(
    id uuid primary key,
    chat_id uuid references chats(id) on update cascade on delete cascade,
    user_id uuid references users(id) on update cascade on delete restrict,
    type message_type not null,
    sent_at timestamp with time zone default current_timestamp not null,

    content varchar(1024)    
);

create index idx_messages_chat_timeline on messages(chat_id, sent_at desc);


