-- 1. create user table
create table users 
(
    -- main
    id int generated by default as identity primary key,
    username varchar(20) unique not null,
    phone varchar(20) not null,
    password_hash varchar(255) not null,

    -- timestamps
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null
);

create index idx_user_username on users(username);
create index idx_user_phone on users(phone);

comment on table users is 'identity "users" table stores sensitive user information';
comment on column users.id is 'unique user id that matches with users(id) of communication db';



-- 2. create operating system enum
create type platform as enum ('web', 'windows', 'macos', 'android', 'ios');



-- 3. create session (or device) table
create table sessions 
(
    -- ids
    id int generated by default as identity primary key,
    user_id int not null references users(id) on update cascade on delete cascade,
    
    -- tokens
    refresh_token varchar(255) unique not null,
    notification_token varchar(255) default '' not null,

    -- device info
    device_hash varchar(255) not null,
    device_name varchar(50) not null,
    device_version varchar(20) not null,
    device_platform platform not null,

    -- audit info
    created_at timestamp with time zone default current_timestamp not null,
    created_ip_address inet not null,
    active_at timestamp with time zone default current_timestamp not null,
    active_ip_address inet not null,

    -- has session been revoked
    is_revoked boolean default false not null
);

create index idx_sessions_user_active on sessions(user_id) where is_revoked = false;

comment on table sessions is 'identity "sessions" table stores all sessions (devices) of users';
comment on column sessions.refresh_token is 'Hash of the refresh token, it uses for validation';
comment on column sessions.notification_token is 'Push Notifications. Stores Apple (APNS) or Google (FCM) tokens so the communication service knows where to route alerts';
comment on column sessions.created_at is 'Date and time when row has been created';
comment on column sessions.created_ip_address is 'The IP Address of device at creation moment';
comment on column sessions.active_at is 'Date and time the device was last used';
comment on column sessions.active_ip_address is 'The IP address of the last device used';

